In [1]:
import numpy as np

In [5]:
arr= np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [8]:
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [11]:
arr[indices_cond]
arr[arr >5]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [13]:
arr[(arr>5)&(arr<9)]

array([6, 7, 8], dtype=int8)

In [16]:
arr[arr>5]=99

In [17]:
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [18]:
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)