In [1]:
import numpy as np

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand()

0.7851434709578221

In [22]:
np.random.rand(4)

array([0.63460968, 0.86947848, 0.66273807, 0.77607189])

In [23]:
np.random.rand(4,4)

array([[0.25415478, 0.74375281, 0.78482252, 0.33528446],
       [0.19730736, 0.97606833, 0.68063345, 0.38448595],
       [0.8893118 , 0.07609916, 0.65329053, 0.78004263],
       [0.17271562, 0.07287699, 0.73208043, 0.73030752]])

In [27]:
np.random.randint(1,15)

10

In [28]:
np.random.randint(1,100,(10,10))

array([[95, 42, 83, 78, 89, 24, 12, 90, 27, 96],
       [45, 92, 89, 47, 13, 19, 32, 15, 43, 30],
       [21, 64, 78, 21, 96, 30, 95, 54, 75, 98],
       [24, 35, 56, 48, 38, 11, 29, 21, 15, 71],
       [94, 11, 70, 21, 57, 85, 48, 81,  1, 56],
       [84, 44, 38, 67, 92, 55, 88, 27,  9, 24],
       [85, 78, 38, 37, 87, 69, 92, 87, 57, 55],
       [22, 35, 82, 85, 31, 17, 95,  8, 21, 93],
       [57, 28, 67, 67,  1, 63, 17, 16, 32, 26],
       [ 6, 17, 22, 71, 20, 53, 98,  1, 93, 63]])