In [2]:
import numpy as np

In [15]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [14]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [10]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [11]:
tensor = np.array([[[1,2,3],[4,5,6],[3,56,2]],[[1,2,3],[4,5,6],[3,56,2]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 3 56  2]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 3 56  2]]]


3

## Agregar o eliminar dimensiones

In [13]:
tensor10 = np.array([1,2,3],ndmin=10)
print(tensor10)
tensor10.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [17]:
expand = np.expand_dims(np.array([1,2,3]),axis =0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [20]:
print(tensor, tensor.ndim)
vector_2 = np.squeeze(tensor)
print(vector_2, vector_2.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 3 56  2]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 3 56  2]]] 3
[[[ 1  2  3]
  [ 4  5  6]
  [ 3 56  2]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 3 56  2]]] 3
