In [1]:
import numpy as np

In [2]:
lista = [1,2]
lista

[1, 2]

In [3]:
lista * 2

[1, 2, 1, 2]

In [5]:
arr = np.arange(0,10)
arr2 = arr.copy()

Operaciones

In [7]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
1/arr

/tmp/ipykernel_14339/255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [14]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [15]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
arr ** arr2

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [17]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()

In [18]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
matriz+matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [20]:
matriz*matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [21]:
matriz-matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [23]:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [24]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

In [25]:
matriz.dot(matriz2.T)

array([[ 30,  80],
       [ 80, 255]])