In [1]:
import numpy as np


In [3]:
arr = np.random.randint(1,10,(3,2))

In [4]:
arr.shape

(3, 2)

In [5]:
arr

array([[1, 6],
       [7, 2],
       [8, 8]])

In [6]:
arr.reshape(1,6)

array([[1, 6, 7, 2, 8, 8]])

In [8]:
arr.reshape(2,3)

array([[1, 6, 7],
       [2, 8, 8]])

In [10]:
np.reshape(arr,(1,6))

array([[1, 6, 7, 2, 8, 8]])

In [11]:
arr

array([[1, 6],
       [7, 2],
       [8, 8]])

In [12]:
np.reshape(arr,(2,3),'C')

array([[1, 6, 7],
       [2, 8, 8]])

In [13]:
np.reshape(arr,(2,3),'F')

array([[1, 8, 2],
       [7, 6, 8]])

In [14]:
np.reshape(arr,(2,3),'A')

array([[1, 6, 7],
       [2, 8, 8]])